// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	FindOverlappingBookings(ctx context.Context, arg FindOverlappingBookingsParams) ([]Booking, error)
	GetBookingByID(ctx context.Context, id pgtype.UUID) (Booking, error)
	InsertBooking(ctx context.Context, arg InsertBookingParams) (Booking, error)
	ListBookedRanges(ctx context.Context, arg ListBookedRangesParams) ([]ListBookedRangesRow, error)
	ListBookingsByStatus(ctx context.Context, status BookingStatus) ([]Booking, error)
	ListPriceOverrides(ctx context.Context, arg ListPriceOverridesParams) ([]ListPriceOverridesRow, error)
	UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) error
}

var _ Querier = (*Queries)(nil)
